from pathlib import Path

import scikitplot as skplt
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np
import numpy.typing as npt

N_CROSS_VALIDATION_MODELS = 10


def plt_plot_chemprop_predictor_roc(
    base_model_path: Path,
    n_cross_validation_models: int = N_CROSS_VALIDATION_MODELS
) -> None:
    """
    Plot ROC curves for the models trained by chemprop.
    
    :param base_model_path: The path to the directory containing the models.
    :param n_cross_validation_models: The number of cross validation models to plot. Default is 10.
    
    :raises FileNotFoundError: If the model directory does not exist.
    :raises ValueError: If the number of cross validation models is less than 1.
    """
    prediction_paths = [
        base_model_path / f"model_{i}_test_preds.csv"
        for i in range(0, n_cross_validation_models)
    ]

    predictions = [pd.read_csv(prediction_path) for prediction_path in prediction_paths]

    _fig, ax = plt.subplots(nrows=3, ncols=3, figsize=(30, 20))

    model_id = 0
    for row in ax:
        for col in row:
            data = predictions[model_id]

            y_truth: npt.NDArray[np.uint16] = data["BBB"].to_numpy()  # ground truth labels
            y_probabilities: npt.NDArray[np.float64] = data[
                "prediction"
            ].to_numpy()  # predicted probabilities generated by sklearn classifier
            y_predictions = np.stack((1 - y_probabilities, y_probabilities), axis=1)

            skplt.metrics.plot_roc(
                y_truth, y_predictions, title=f"Model {model_id}", ax=col
            )
            model_id += 1
