name: combinatorial_antibiotics

channels:
  - conda-forge
  - rdkit
  - pytorch

dependencies:
  - python>=3.10
  - hyperopt  # for chemprop
  - ipdb  # for debugging
  - ipython  # for debugging
  - matplotlib
  - numpy
  - pandas
  - pip
  - pytorch  # for chemprop
  - rdkit
  - scikit-learn
  - scipy
  - tensorboardX  # for chemprop
  - tqdm
  - umap-learn  # for chem_utils
  - pip:
    - typed-argument-parser
    - git+https://github.com/bp-kelley/descriptastorus
